main: fr.will33.armsrush.ArmsRush
name: ArmsRush
version: ${project.version}
api-version: "1.20"
author: William AVENTIN
website: "https://www.elesia.org"
commands:
  armsrush:
    description: "Commande administrative"
  configuration:
    description: "Configurer l'arène"
  prestart:
    description: "Se préparer pour le début de la partie"